#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giaodiendieukhien
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GATTHAN_DATA")]
	public partial class Excel_ReportDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public Excel_ReportDataContext() : 
				base(global::Giaodiendieukhien.Properties.Settings.Default.GATTHAN_DATAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Excel_ReportDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Excel_ReportDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Excel_ReportDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Excel_ReportDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Bunke1_data> Bunke1_datas
		{
			get
			{
				return this.GetTable<Bunke1_data>();
			}
		}
		
		public System.Data.Linq.Table<Bunke2_data> Bunke2_datas
		{
			get
			{
				return this.GetTable<Bunke2_data>();
			}
		}
		
		public System.Data.Linq.Table<Bunke3_data> Bunke3_datas
		{
			get
			{
				return this.GetTable<Bunke3_data>();
			}
		}
		
		public System.Data.Linq.Table<Devices_data> Devices_datas
		{
			get
			{
				return this.GetTable<Devices_data>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bunke1_data")]
	public partial class Bunke1_data
	{
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _date_time;
		
		private System.Nullable<double> _loadcell1_data;
		
		public Bunke1_data()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_time
		{
			get
			{
				return this._date_time;
			}
			set
			{
				if ((this._date_time != value))
				{
					this._date_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loadcell1_data", DbType="Float")]
		public System.Nullable<double> loadcell1_data
		{
			get
			{
				return this._loadcell1_data;
			}
			set
			{
				if ((this._loadcell1_data != value))
				{
					this._loadcell1_data = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bunke2_data")]
	public partial class Bunke2_data
	{
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _date_time;
		
		private System.Nullable<double> _loadcell2_data;
		
		public Bunke2_data()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_time
		{
			get
			{
				return this._date_time;
			}
			set
			{
				if ((this._date_time != value))
				{
					this._date_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loadcell2_data", DbType="Float")]
		public System.Nullable<double> loadcell2_data
		{
			get
			{
				return this._loadcell2_data;
			}
			set
			{
				if ((this._loadcell2_data != value))
				{
					this._loadcell2_data = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bunke3_data")]
	public partial class Bunke3_data
	{
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _date_time;
		
		private string _sensor_status;
		
		public Bunke3_data()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_time
		{
			get
			{
				return this._date_time;
			}
			set
			{
				if ((this._date_time != value))
				{
					this._date_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sensor_status", DbType="NVarChar(50)")]
		public string sensor_status
		{
			get
			{
				return this._sensor_status;
			}
			set
			{
				if ((this._sensor_status != value))
				{
					this._sensor_status = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Devices_data")]
	public partial class Devices_data
	{
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _date_time;
		
		private string _device_name;
		
		private string _device_status;
		
		private string _note;
		
		public Devices_data()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_time
		{
			get
			{
				return this._date_time;
			}
			set
			{
				if ((this._date_time != value))
				{
					this._date_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_device_name", DbType="NVarChar(50)")]
		public string device_name
		{
			get
			{
				return this._device_name;
			}
			set
			{
				if ((this._device_name != value))
				{
					this._device_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_device_status", DbType="NVarChar(50)")]
		public string device_status
		{
			get
			{
				return this._device_status;
			}
			set
			{
				if ((this._device_status != value))
				{
					this._device_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="NVarChar(50)")]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this._note = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
